In [1]:
import h5py
import numpy as np

# Open the file
with h5py.File('/localdata/commondata/test.hd5', 'r') as f:
    # Explore the top-level groups
    print("Top-level groups:", list(f.keys()))
    
    # Access 'halo' group
    h_group = f['halo']
    h_mass = h_group['mass'][:]
    h_mass_log10 = np.log10(h_mass)
    h_x = h_group['x'][:]
    h_y = h_group['y'][:]
    h_z = h_group['z'][:]
    h_sigma = h_group['sigma'][:]
    h_velocity = h_group['velocity'][:]
    
    # Access 'subsample' group
    s_group = f['subsample']
    s_mass = s_group['mass'][:]
    s_mass_log10 = np.log10(s_mass)
    s_x = s_group['x'][:]
    s_y = s_group['y'][:]
    s_z = s_group['z'][:]
    s_velocity = s_group['velocity'][:]
    s_n_particles = s_group['n_particles'][:]

Top-level groups: ['halo', 'subsample']


In [2]:
import galpopc

In [4]:
import time

start = time.perf_counter()
x, xs, y, ys, zr, zsr, z, zs = galpopc.populate_galaxies(
    # Halo arrays
    h_mass_log10, h_x, h_y, h_z, h_velocity, h_sigma,
    # Subhalo arrays
    s_mass_log10, s_mass, s_velocity, s_n_particles, s_x, s_y, s_z, s_velocity,
    # HOD parameters
    12.5, 0.1, 13.5, 1.0, 1.0, 0.0, 1.0,
    # Other parameters
    True, -1000.0, 1000.0
)
end = time.perf_counter()

print(f"Elapsed time: {end - start:.6f} seconds")

Elapsed time: 1.559974 seconds


In [10]:
zr

array([-101.97296 ,  -19.712122,  165.08601 , ..., -992.6103  ,
       -418.99783 ,  525.1388  ], dtype=float32)

In [11]:
zsr

array([-376.084,  201.27 ,  201.278, ...,  133.374, -672.522, -673.204],
      dtype=float32)

In [12]:
z

array([ -97.82207 ,  -23.158543,  164.34415 , ..., -997.7888  ,
       -415.7269  ,  525.2798  ], dtype=float32)

In [13]:
zs

array([-389.0651 ,  210.20073,  201.1452 , ...,  136.62756, -677.96674,
       -668.4564 ], dtype=float32)

In [14]:
h_velocity

array([-3.9579225 ,  5.9596148 , -0.54115343, ..., -3.0291314 ,
        4.6268167 , -3.3572586 ], dtype=float32)

In [16]:
np.min(h_velocity)

-29.712399

In [30]:
np.min(z)


-1014.80615