In [1]:
import h5py
import numpy as np

# Open the file
with h5py.File('/localdata/commondata/test.hd5', 'r') as f:
    # Explore the top-level groups
    print("Top-level groups:", list(f.keys()))
    
    # Access 'halo' group
    h_group = f['halo']
    h_mass = h_group['mass'][:]
    h_mass_log10 = np.log10(h_mass)
    h_x = h_group['x'][:]
    h_y = h_group['y'][:]
    h_z = h_group['z'][:]
    h_sigma = h_group['sigma'][:]
    h_velocity = h_group['velocity'][:]
    
    # Access 'subsample' group
    s_group = f['subsample']
    s_mass = s_group['mass'][:]
    s_mass_log10 = np.log10(s_mass)
    s_x = s_group['x'][:]
    s_y = s_group['y'][:]
    s_z = s_group['z'][:]
    s_velocity = s_group['velocity'][:]
    s_n_particles = s_group['n_particles'][:]

Top-level groups: ['halo', 'subsample']


In [2]:
import galpopc

In [4]:
galpopc.populate_galaxies(
    # Halo arrays
    h_mass_log10, h_x, h_y, h_z, h_velocity, h_sigma,
    # Subhalo arrays
    s_mass_log10, s_mass, s_velocity, s_n_particles, s_x, s_y, s_z, s_velocity,
    # HOD parameters
    13.0, 0.1, 13.5, 1.0, 1.0, 0.0, 1.0,
    # Other parameters
    True, -1000.0, 1000.0
)

(array([-58.269783, -58.085327, -58.388054, ..., 822.255   , 822.77826 ,
        822.3056  ], dtype=float32),
 array([ 999.405  , -998.28827, -996.64233, ...,  987.9647 ,  994.8288 ,
         997.69037], dtype=float32),
 array([ -97.82207 ,  -23.158543,  665.42957 , ..., -459.02484 ,
         374.75842 , -415.7269  ], dtype=float32),
 array([-58.508, -58.264, -58.258, ..., 822.01 , 822.392, 822.8  ],
       dtype=float32),
 array([-990.956, -987.292, -987.44 , ...,  988.152,  987.904,  994.762],
       dtype=float32),
 array([ 670.5997 ,  630.90436,  620.20764, ..., -453.41608, -451.7837 ,
         367.4872 ], dtype=float32))